# Generated by Django 5.0.6 on 2024-05-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('time', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=65, null=True)),
                ('restaurant', models.CharField(max_length=8, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
