# Generated by Django 5.0.6 on 2024-05-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='time',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
