# Generated by Django 5.0.6 on 2024-05-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_place_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
