# Generated by Django 3.2 on 2024-05-30 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='food.place'),
        ),
    ]
