# Generated by Django 5.0.6 on 2024-05-31 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_photo_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='photo',
            name='place',
            field=models.ForeignKey(help_text='The place that this photo come from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='food.place'),
        ),
    ]
