# Generated by Django 5.0.6 on 2024-05-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_place_restaurant_alter_photo_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='off_day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
