# Generated by Django 5.0.6 on 2024-05-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_place_off_day_place_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='food',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
