# Generated by Django 3.2 on 2024-06-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_place_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='off_day',
        ),
    ]
